DO $$
BEGIN
  CREATE TYPE "EmailAccountType" AS ENUM ('LEAD_INTAKE', 'SALES_SENDER', 'ADMIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "email_accounts"
  ADD COLUMN IF NOT EXISTS "accountType" "EmailAccountType" NOT NULL DEFAULT 'SALES_SENDER';

ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'WAITING_FOR_SANDIP';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'HOLD';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL_SENT';
