ALTER TABLE "drafts"
  ADD COLUMN IF NOT EXISTS "toEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "ccEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "bccEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "trackingEnabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "sent_emails"
  ADD COLUMN IF NOT EXISTS "bccEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
